# Generated by Django 3.0.4 on 2020-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Should contain only text'),
        ),
    ]
